ERROR 2024-10-11 11:21:56,639 log Internal Server Error: /internship/
Traceback (most recent call last):
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Priyesh Pandey\OneDrive\Desktop\agratas\AIPL_SOURCE_CODE\AIPL_WEB_ERP\AIPL\views.py", line 438, in internship_opportunity_page
    return render(request, 'Internship/internship.html')
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\contrib\staticfiles\storage.py", line 166, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\contrib\staticfiles\storage.py", line 145, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\Priyesh Pandey\AppData\Roaming\Python\Python310\site-packages\django\contrib\staticfiles\storage.py", line 465, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'img/internship_background.jpg'
ERROR 2024-10-11 11:21:56,641 basehttp "GET /internship/ HTTP/1.1" 500 145
